version: '3.8'
services:
    eureka-service:
      build: 
        context: ./eureka
      image: eureka-service:latest
      container_name: eureka
      ports:
        - 8761:8761
      hostname: eureka
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
      # networks: 
      #   - mynetwork
    config-service:
      build: 
        context: ./configServer
      image: config-server:latest
      ports:
        - 8888:8888 
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
      depends_on: 
        - eureka-service
      network_mode: host
    proxy-service:
      build: 
        context: ./web-cv-proxy
      image: zuul-service:latest
      ports:
        - 8081:8081
      depends_on: 
        - config-service
        - eureka-service
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
      # networks: 
      #   - mynetwork
    auth-service:
      build: 
        context: ./web-based-cv/auth-service
      image: auth-service:latest
      ports:
        - 8060:8060
      deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
      depends_on: 
        - config-service
        - eureka-service
        - proxy-service
      restart: on-failure
      network_mode: host
      # networks: 
      #   - mynetwork
    portal-service:
      build: 
        context: ./web-based-cv/cv-portal
      image: cv-portal:latest
      ports:
        - 9090:9090
      deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
      depends_on: 
        - config-service
        - eureka-service
        - proxy-service
      restart: on-failure
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
      network_mode: host
#       networks: 
#         - mynetwork
# networks: 
#   mynetwork:
#     driver: bridge     