version: '3.8'
services:
    redis-dkr:
      image: "redis"
      command: --protected-mode no
      ports:
        - '6379:6379'
    openzipkn:
      image: "openzipkin/zipkin"
      ports:
        - '9411:9411'
    eureka:
      build: 
        context: ./eureka
      image: eureka-service:latest
      container_name: eureka
      ports:
        - '8761:8761'
    zookeeper:
      image: 'bitnami/zookeeper:latest'
      ports:
        - '2181:2181'
      environment:
        - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
      image: 'bitnami/kafka:latest'
      ports:
        - '9092:9092'
      environment:
        - KAFKA_BROKER_ID=1
        - KAFKA_LISTENERS=PLAINTEXT://:9092
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
      depends_on:
        - zookeeper
    