version: '3'
services:
    eureka-service:
      image: eureka-service:latest
      container_name: eureka
      ports:
        - 8761:8761
      hostname: eureka
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
    config-service:
      image: configServer:latest
      ports:
        - 8888:8888
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka    
    proxy-service:
      image: zuul-service:latest
      ports:
        - 8081:8081
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
      depends_on: 
        - config-service
    auth-service:
      image: auth-service:latest
      ports:
        - 8060:8060
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
      depends_on: 
        - config-service
    portal-service:
      image: cv-portal:latest
      ports:
        - 9090:9090
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
      depends_on: 
        - config-service
