server:
  port: 8081

spring:
  application:
    name: zuul-proxy

zuul:
  sensitiveHeaders: Cookie,Set-Cookie,Authorization
  routes:
    auth-service:
      path: /api/auth/**
      serviceId: auth-service       # Translated as http://localhost:8081/auth-service/api/auth/user/login-form
    cv-service:
      path: /api/cv/**
      serviceId: cv-service         # Translated as http://localhost:8081/cv-service/api/cv/**
    auth-server:
      path: /oauth/**
      serviceId: auth-server       # Translated as http://localhost:8081/auth-server/oauth/**

ribbon:
  MaxConnectionsPerHost: 1000
  MaxTotalConnections: 3000
  ReadTimeout: 10000
  ConnectTimeout: 2000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  ServerListRefreshInterval: 1000
  NFLoadBalancerPingInterval: 5

eureka:
  client:
    fetchRegistry: true
    register-with-eureka: true
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
    registry-fetch-interval-seconds: 3

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
