server:
  port: 8081

spring:
  application:
    name: zuul-proxy

zuul:
  routes:
    auth-service:
      path: /api/auth/**
      serviceId: auth-service       # Translated as http://localhost:8081/auth-service/api/auth/user/login-form
    cv-service:
      path: /api/cv/**
      serviceId: cv-service         # Translated as http://localhost:8081/cv-service/api/cv/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


