server:
  port: 8081
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-alias: sweelam-cv
    key-store-password: sweelam_2014

spring:
  application:
    name: zuul-proxy

zuul:
  routes:
    auth-service:
      path: /api/auth/**
      serviceId: auth-service       # Translated as http://localhost:8081/auth-service/api/auth/user/login-form
    cv-service:
      path: /api/cv/**
      serviceId: cv-service         # Translated as http://localhost:8081/cv-service/api/cv/**

ribbon:
  ReadTimeout: 120000               # To avoid timeout on server

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

