server:
  port: 8081

spring:
  application:
    name: zuul-proxy

zuul:
  routes:
    auth-service:
      path: /api/auth/**
      serviceId: auth-service       # Translated as http://localhost:8081/auth-service/api/auth/user/login-form
    cv-service:
      path: /api/cv/**
      serviceId: cv-service         # Translated as http://localhost:8081/cv-service/api/cv/**

ribbon:
  MaxConnectionsPerHost: 1000
  MaxTotalConnections: 3000
  ReadTimeout: 10000
  ConnectTimeout: 2000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  ServerListRefreshInterval: 1000
  NFLoadBalancerPingInterval: 5

eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
  instance:
    prefer-ip-address: true
    registry-fetch-interval-seconds: 3
