spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT `KEY`, `VALUE` from `properties` where APPLICATION=? and PROFILE=? and LABEL=?
          order: 1
    stream:
      kafka:
        binder:
          brokers: localhost:9092
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sweprofile?zeroDateTimeBehavior=convertToNull
    username: sweelam
    password: sweelam&roka
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
  profiles:
    active: jdbc

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: ["health","info","refresh", "bus-refresh"]
