spring:
  datasource:
    jpa:
      properties:
        hibernate:
          format_sql: true
          ddl-auto: none
  application:
    name: auth-service
    bus:
      refresh:
        enabled: true
    profiles:
      active: jdbc
  cloud:
    retry:
      initial-interval: 1500
      multiplier: 1.5
      max-attempts: 10000
      max-interval: 1000
    config:
      discovery:
        enabled: true
        service-id: configServer
  config:
    import: optional:configserver:http://configServer:8888
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  servlet:
    context-path: /api/auth
  port: 8060

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
      health:
        show-details: ALWAYS

eureka:
  client:
    fetchRegistry: true
    register-with-eureka: true
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
    registry-fetch-interval-seconds: 3
    metadata-map:
      management:
        context-path: "/api/auth/actuator"

