spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: sweelam
    password: sweelam&roka
    url: jdbc:mysql://localhost:3306/sweprofile?zeroDateTimeBehavior=convertToNull
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
      
server:
  port: 8060
  servlet:
    context-path: /api/auth

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true